### ISSUE TITLE
[FEATURE] Automated Testing

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#485]
**Is your feature request related to a problem? Please describe.**
As the project becomes increasingly complex it becomes less and less feasible to validate changes and look for side-effects by hand.

**Describe the solution you'd like**
Automated test coverage.

**Additional context**
We already have the building blocks of unit testing with a few preliminary Jest tests. We should expand coverage, as well as get started on Cypress e2e tests

**Subtasks**
- [ ] Integrate Cypress and get a basic e2e set up
- [ ] Determine (or confirm) the test protocols and styles we want to conform to
- [ ] Unit Testing for all Classes (and associated game logic files)
- [ ] Unit Testing for all CC-Components
- [ ] Unit Testing for all other features
- [ ] Comprehensive e2e tests

**Comment by aritsune** [comment]
Assigning to myself to set up Cypress

**Comment by IcyCrane37** [comment]
Do y'all still need help with this?
I haven't unit tested in a bit but my day job is software verification testing on embedded systems and I help lead a test team.
I should still have some unit testing chops! 
Only thing is I haven't ever worked with testing web-based things.
