### ISSUE TITLE
[FEATURE] Animated Transitions

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#496]
**Is your feature request related to a problem? Please describe.**
Active Mode/Encounter Runner round and encounter transitions are abrupt and unsatisfying, and can easily be overlooked.

**Describe the solution you'd like**
Flavorful, animated screen transitions mark movement between rounds or encounters. Expansions on this might be pilot states (mounted/unmounted/ejected/mech destroyed/reactor destroyed/pilot death)

**Additional context**
I'm imagining something like Destiny 2's PvP rank-ups: https://youtu.be/MDPE7mhgrmE?t=32

**Subtasks**
- [ ] Active Mode turn transitions
- [ ] Encounter Runner round transitions
- [ ] Encounter Runner encounter transitions
