### ISSUE TITLE
[FEATURE] Item Actions

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#519]
**Is your feature request related to a problem? Please describe.**
Currently, many mech systems (and some weapons) contain or describe specific types of combat actions (tech attacks, protocols, reactions, etc). Now that data is more-or-less finalized, we should format this information so C/C can reason about it (and we can provide more options to the forthcoming homebrew UI)

**Describe the solution you'd like**
We should identify the game-mechanical elements of system and weapon effects, and modify the item data structure to contain this information. Once we have this done, we can create new UI elements for each type as a first step towards porting more game logic into C/C

**Additional context**
This feature collects https://github.com/massif-press/compcon/issues/85. Issues https://github.com/massif-press/compcon/issues/88 , https://github.com/massif-press/compcon/issues/89 , and https://github.com/massif-press/compcon/issues/92 are closed and will be readressed after this feature is completed. 
Parent task of #587 

**Subtasks**
- [ ] Determine item effect types/actions
- [ ] Modify item data structure
- [ ] Update lancer-data
- [ ] Implement new UI elements

**Comment by jarena3** [comment]
A (wip) list of the Mech System effect types I've identified, should be stored as an array because several items have multiple effects/actions:
- Passive Effect
- Quick Activation Effect
- Full Activation Effect
- Drone
- Charge
- Stat Bonus
- Protocol
- Deployable
- Tech Invasion Option
- Reaction
- Quick Tech Option
- Full Tech Option
